#!/usr/bin/env bash
# Print "Best School" 10 times
# For the 9th iteration, also print "Hi" on a new line

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((count++))
done

